on: push
name: Optimize SVGs
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: '10.x'
      - run: npm install svgo
      - run: npm run svgo
      - uses: EndBug/add-and-commit@v4
        with:
          add: 'icons'
          message: 'chore: Optimize SVGs.'
          author_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
